### PR TITLE
resolves #1

### LINKED ISSUE #1: todo list for completion of seccomp-pledge
Great work on the project and related materials, @DeviousCilantro! 🎉 Keep up the good work. We're now going to use this issue to create a checklist of small tasks that still need to be done.

- [x] Run `cargo clippy -- -W clippy::pedantic` and apply appropriate changes (you might wanna read all of them as some might cause regression, you can apply them automatically using `cargo clippy --fix -- -W clippy::pedantic` but best to go through them)
- [x] Move checks for BIF JIT, dependencies, etc. out of the `fn main` function. This way, we can avoid a bit of overhead. Instead, we should ideally have a `fn check()` function that is called through a command line argument, such as `-check` or `-no_check`.
- [x] Tests: We can launch commands like `ls` with and without restrictions (`ls` the project folder) to see if we get the expected output.
- [x] Benchmarks: While there may not be a specific need for them, we will include tests in the benchmarking process for the sake of completeness.
- [x] Non-interactive mode: The current program runs in an interactive way, but we should also have a simple one-liner, for example: `./seccomp_pledge -check -v -p 'stdio rpath' ls` similar to `pledge`.
- [x] Add more examples in `README`

Don't worry about `CI` and other things, I will update the project with it, along with the skeleton for tests and benchmarks. A few good starting points for you might be:

A few good starting points for you might be: 
- [writing tests](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) and [writing tests for command line](https://rust-cli.github.io/book/tutorial/testing.html)
- [benchmarking](https://bheisler.github.io/criterion.rs/book/getting_started.html), just throw every test inside `blackbox`
- [Command Line Applications in Rust](https://rust-cli.github.io/book/index.html)

### PR DESCRIPTION
**Pull request by DeviousCilantro**
completed all tasks mentioned in #1 with some additional refactoring

### CODE REVIEW

**Review by sn99 — CHANGES_REQUESTED** [review]
@DeviousCilantro Nice work again and pretty fast at it too, I think we add a few examples on how to use this, somewhere in `README.md`. We have a lot of commands/args and different modes and we don't want people trying to discover them on their own.

**Comment by DeviousCilantro** [comment]
Certainly. I was actually planning to update `README.md` with details of all the changes implemented after figuring out how to incorporate Unix socket API support as @dilawar had suggested, which I would also demonstrate in the README. But sure, I will add some examples for now.

**Comment by DeviousCilantro** [comment]
@sn99 I have updated `README.md` with more examples/demos, added a quick overview of the available flags and added `pledge` as a local binary with the option to fetch from upstream too. Feel free to review and merge the commits if deemed appropriate.

**Comment by DeviousCilantro** [comment]
I have also implemented Unix socket API support and provided some details about it in the README. Will add an example/demo for it soon.

**Comment by DeviousCilantro** [comment]
Added examples/demos for the three modes (interactive, non-interactive, API) of interacting with seccomp-pledge and updated the README. Let me know if there is anything else left to be done.

**Comment by sn99** [comment]
@dilawar I don't have merge access, I think we can merge it for now and see where we go from there

**Pull request merged**
